version: '3'

services:

    certbot:
        image: certbot/certbot:latest
        volumes:
            - ./certbot/www/:/var/www/certbot/:rw

    frontend_web:
        build:
            context: frontend_web/
            dockerfile: Dockerfile
        ports:
            - "80:80"
        expose:
            - "80"

    backend:
        build:
            context: backend/
            dockerfile: Dockerfile
        ports:
            - "8080:8080"