# Generated by Django 3.2.12 on 2022-09-28 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=350)),
                ('title_img_url', models.TextField(blank=True, null=True)),
                ('servings', models.IntegerField(blank=True, null=True)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('view_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ingredient_amount', models.TextField(blank=True, null=True)),
                ('ingredient_id', models.ForeignKey(db_column='ingredient_id', on_delete=django.db.models.deletion.DO_NOTHING, to='recipes.ingredient')),
                ('recipe_id', models.ForeignKey(db_column='recipe_id', on_delete=django.db.models.deletion.DO_NOTHING, to='recipes.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeDetail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('recipe_step', models.IntegerField()),
                ('recipe_content', models.TextField()),
                ('recipe_img_url', models.TextField(blank=True, null=True)),
                ('recipe_id', models.ForeignKey(db_column='recipe_id', on_delete=django.db.models.deletion.DO_NOTHING, to='recipes.recipe')),
            ],
        ),
    ]
