# Generated by Django 3.2.12 on 2022-09-28 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tips',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tip_content', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
